namespace IdentityProvider.API.Controllers
{
    using Entities;
    using Helpers;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;

    [Route("jwks")]
    public class JwksController : BaseController
    {
        /// <summary>
        /// The JWT token helper
        /// </summary>
        private readonly JwtTokenHelper _jwtTokenHelper;

        public JwksController(IOptions<ConfigSettings> configSettings,
            JwtTokenHelper jwtTokenHelper) : base(configSettings)
        {
            this._jwtTokenHelper = jwtTokenHelper;
        }

        /// <summary>
        /// Gets the custom token (generated by means of standard .NET Core libraries) with Session ID.
        /// </summary>
        /// <returns>The JSON object with token and Session ID.</returns>
        [HttpGet]
        public ContentResult GetManualJsonWebKeySet()
        {
            return this.Content(this._jwtTokenHelper.RsaKeyData.JsonWebKeySetSerialized, "application/json");
        }
    }
}
